{{- $data := dict -}}
{{- range $field := include "smg.secretFields" . | fromJsonArray -}}
{{- if and $field.value (kindIs "string" $field.value) -}}
{{- $_ := set $data $field.key $field.value -}}
{{- end -}}
{{- end -}}
{{- if $data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "smg.fullname" . }}-secrets
  labels:
    {{- include "smg.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml $data | nindent 2 }}
{{- end }}
